database:
  user: user
  pass: secret
  host: localhost
  port: 5432
  db_name: NexaFormDB

server:
  http_port: 8080
  token_exp_minutes: 1440
  refresh_token_exp_minutes: 2880
  token_secret: "P@$$%Secret6677"