version: '3.8'

services:
  nexaform-redis:
    image: redis/redis-stack:latest
    container_name: nexaform-redis
    ports:
      - "8003:8001"
      - "6380:6379"
    volumes:
      - nexaform-redis-volume:/data
    networks:
      - nexaform-network

  nexaform-db:
    image: postgres:latest
    container_name: nexaform-db
    restart: always
    environment:
      POSTGRES_DB: NexaFormDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - nexaform-db-volume:/var/lib/postgresql/data
    networks:
      - nexaform-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - ./Logs:/var/log/my-service
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks:
      - nexaform-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/data
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - nexaform-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - nexaform-network

  minio:
    image: quay.io/minio/minio
    container_name: nexaform-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_NOTIFY_REDIS_ENABLE_PRIMARY: "on"
      MINIO_NOTIFY_REDIS_ADDRESS_PRIMARY: "nexaform-redis:6379"
      MINIO_NOTIFY_REDIS_KEY_PRIMARY: "bucketevents"
      MINIO_NOTIFY_REDIS_FORMAT_PRIMARY: "namespace"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - nexaform-network
    depends_on:
      - nexaform-redis


volumes:
  nexaform-db-volume:
  nexaform-redis-volume:
  loki-data:
  grafana-data:
  minio-data:

networks:
  nexaform-network:
    driver: bridge
